<?php

namespace OC\PlatformBundle\Repository;

/**
 * ApplicationMailerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationMailerRepository extends \Doctrine\ORM\EntityRepository
{
}
