<?php

namespace OC\PlatformBundle\Repository;

/**
 * PoubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoubRepository extends \Doctrine\ORM\EntityRepository {
 public function removeMemsMoi() {
     
     
 }
    public function getMemsMoi() {
//          $em = $this->getDoctrine()->getManager();
//    $adverts = $em->getRepository('OCPlatformBundle:Advert')->findAll();
//   
        // $query = $this->_em->createQuery('SELECT a FROM  OCPlatformBundle:Advert a WHERE count(a.categories intersect  :categoryNamess) = count(:categoryNamess)');
        //https://dev.mysql.com/doc/refman/5.5/en/exists-and-not-exists-subqueries.html
        //$query = $this->_em->createQuery('SELECT a FROM  OCPlatformBundle:Advert a1 WHERE exists(select * from OCPlatformBundle:Advert a2 where a2.)');
        //  $query->setParameter('categoryNamess', $categoryNames);
//        $query = $this->_em->createQuery('SELECT a FROM  OCPlatformBundle:Advert a');
//        return $query->getResult();


        $query = $this->_em->createQuery('SELECT p FROM OCPlatformBundle:Poub p');
        $results = $query->getResult();
        return $results;
    }

}
